function [fitresult, gof] = createFit(xData, yData, z)
%CREATEFIT(XDATA,YDATA,Z)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : xData
%      Y Input : yData
%      Z Output: z
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 01-Sep-2015 22:03:17


%% Fit: 'untitled fit 1'.
[xData_1, yData_1, zData] = prepareSurfaceData( xData, yData, z );

% Set up fittype and options.
ft = fittype( 'loess' );
opts = fitoptions( 'Method', 'LowessFit' );
opts.Normalize = 'on';
opts.Span = 0.01;

% Fit model to data.
[fitresult, gof] = fit( [xData_1, yData_1], zData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, [xData_1, yData_1], zData );
legend( h, 'untitled fit 1', 'z vs. xData, yData', 'Location', 'NorthEast' );
% Label axes
xlabel xData
ylabel yData
zlabel z
grid on


